set $background /const/workflow/homeDir/dotLocal/bg/Yamada_Ryo.png

output DP-1 {
    mode 2560x1440@170.001Hz
    pos 0 0
    res 2560x1600
    scale 1
    bg $background stretch
}

default_border none
default_floating_border none
gaps inner 2
gaps outer 2
