set $background /const/workflow/homeDir/dotLocal/bg/Yamada_Ryo.png

output eDP-1 {
    mode 2560x1660@120.001Hz
    pos 0 0
    res 2560x1600
    scale 1.5
    bg $background fill
}

default_border none
default_floating_border none
gaps inner 0
gaps outer 0
